### ISSUE TITLE
Using pip install libecl on Window?

### ISSUE THREAD

**Issue by cuthbertng94** [equinor/resdata#726]
Hello, I am wondering if there is any clearer instruction of installing libecl on window? Thank you.

**Comment by dotfloat** [comment]
You need to have some C++ compiler (eg. Visual Studio 2015+), CMake, Python and git. Open a new command prompt (or powershell), make sure all are accessible, and then you should be able to follow the same steps as the Linux/macOS install.

**Comment by cuthbertng94** [comment]
If I am using jupyter notebook by Anaconda, then I just need to do the installation of Visual Studio 2015+, CMake, Python and git on the Anaconda prompt? Then after that I am able to pip install the libecl?

**Comment by dotfloat** [comment]
The simplest thing you can do is use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10), which installs an Ubuntu VM that you can interact with as a Windows user. Then simply `pip install libecl`.

Unfortunately, you can't pip install libecl on normal Windows at this moment. You need to follow the [**Alternative 3**](https://github.com/equinor/libecl#alternative-3-c-library-with-python-bindings) installation guide if you want to have a native solution. (If you do end up getting this working I'd be very happy to include the steps you used in the README)

**Comment by trhallam** [comment]
So I was able to get a pretty easy install going for v2.9.4. I have msvc.exe from VS 2017 installed and I edited the `setup.py` to include a windows platform specific link the compiled library.

```
    def dlopen_libecl():
        import ctypes
        import platform

        path = os.path.join(os.path.dirname(__file__), ".libs")
        if platform.system() == "Linux":
            path = os.path.join(path, "libecl.so")
        elif platform.system() == "Darwin":
            path = os.path.join(path, "libecl.dylib")
        elif platform.system() == "Windows":
            path = os.path.join(os.path.dirname(__file__), ".bin", "libecl.dll")**
        else:
            raise NotImplementedError("Invalid platform")
```

I'm not sure why but with the Windows compiler the dll ends up in the bin folder, not .libs.

This then works by running 
```
python setup.py install
```
in the top level directory.

I've never had an issue with the ecl functionality under windows, is there a reason we can't add a windows wheel to pypi deployment pipeline?

**Comment by crayxt** [comment]
@trhallam The almost same patch for finding libecl on Windows is merged now as https://github.com/equinor/ecl/pull/752, and will be present in upcoming release(s).
I've definitely see the issue on Windows the same as https://github.com/equinor/ecl/issues/604

**Comment by dotfloat** [comment]
The reason we don't have a Windows wheel is because of lack of time really (and because internally nobody uses Windows for libecl-related stuff). I've recently acquired Windows 10 + Visual Studio licenses so I'll set it up it when time allows. It's in my backlog. :)

**Comment by trhallam** [comment]
Awesome, understand @dotfloat about the time thing. If I can help out somehow just let me know.

**Comment by dotfloat** [comment]
I gave it another try and didn't get anywhere. Was trying to get the Python bindings to work at all. I have the Python from Windows 10 store (3.9, x64). Successfully built with `pip install .` using MSVC 2019. However, when importing `ecl` it fails when trying to load the `libecl.dll` file, complaining that it's not a valid DLL. I'm assuming there's a mismatch between the architectures, ie. `libecl.dll` is x86.

How did you get it to work?

For the record, in order to get automated PyPI builds I need to figure out:
1. Compile and test `libecl.dll` by itself using the C Tests.
2. Figure out whether I need to compile two different Windows packages, one for x86 and for x64.
3. Build with `pip wheel .`
4. Test using `pytest python/tests -v`

(Basically, I need add Windows to all of the steps in the Github Actions workflow, https://github.com/equinor/ecl/blob/master/.github/workflows/testing.yml)

**Comment by trhallam** [comment]
I'm on x64 windows. I'm not sure I have a 32bit MSVC compiler so it may just be suited to my system. I suspect you will need an architecture specific dll. 

I'll make a fork and have a look at the Github Actions workflow.

**Comment by trhallam** [comment]
@dotfloat , so here is the rub. I don't think Github actions provides any 32bit images. So we can build a 32 bit windows lib, but we can't test it on the build system. Do you want to offer 32 bit libs? I don't think you do that for ubuntu or mac at the moment.

If you are happy to go with 64bit only I can modify the workflow and submit a pull request once it is tested in my fork.

**Comment by dotfloat** [comment]
To my knowledge, MSVC provides both x86 and x64 compilers, and x86 Python should work on x64, so as long as Github provides a x64 image, then we're set.

We don't provide x86 Linux or macOS builds because both have had excellent x64 support. Whereas in the Windows world people still depend on x86 working. It could be my own bias though. It's not something that I want to support, but I'll have to ask around whether it's something we want to support.

The Python installed via the Microsoft store is x64, which is fine. Seems like either https://github.com/scikit-build/scikit-build or `ninja` have some bug that builds an x86 `.dll`, but I'm not certain.

If you can do the 64-bit then ye, would be great to have a PR on it!

**Comment by trhallam** [comment]
Oh ok, 

Well, using the same setup as on Github (VS 2019 v16) I have to modify the cmake command like this.


```          
mkdir cmake-build
cmake -S . -B cmake-build -G "Visual Studio 16 2019" -A "x64" -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build cmake-build
```

Which passes fine. But then I get errors in `ctest`

```
PS C:\dev\source\ecl\cmake-build> $Env:ECL_SKIP_SIGNAL = "absolutely"
PS C:\dev\source\ecl\cmake-build> $Env:ERT_SHOW_BACKTRACE = "yes please!"
PS C:\dev\source\ecl\cmake-build> ctest --output-on-failure
Test project C:/dev/source/ecl/cmake-build
        Start   1: ert_util_alloc_file_components
Test not available without configuration.  (Missing "-C <config>"?)
  1/114 Test   #1: ert_util_alloc_file_components .......***Not Run   0.00 sec
        Start   2: ert_util_split_path
Test not available without configuration.  (Missing "-C <config>"?)
  2/114 Test   #2: ert_util_split_path ..................***Not Run   0.00 sec
        Start   3: ert_util_approx_equal
Test not available without configuration.  (Missing "-C <config>"?)
  3/114 Test   #3: ert_util_approx_equal ................***Not Run   0.00 sec
        Start   4: ert_util_before_after
Test not available without configuration.  (Missing "-C <config>"?)
  4/114 Test   #4: ert_util_before_after ................***Not Run   0.00 sec
        Start   5: ert_util_binary_split

**Comment by dotfloat** [comment]
You're outside the build dir:
```
ctest -C cmake-build --output-on-failure
```

**Comment by trhallam** [comment]
The previous post was in the build dir `cmake-build` no? You have the line `cd cmake-build` in the `run tests` actions.

Anyway, I tried a few different configurations of the command in the project and build directory. Still no joy.
```
PS C:\dev\source\ecl> ctest -C cmake-build --output-on-failure
Test project C:/dev/source/ecl
No tests were found!!!
PS C:\dev\source\ecl> cd cmake-build
PS C:\dev\source\ecl\cmake-build> ctest -C cmake-build --output-on-failure
Test project C:/dev/source/ecl/cmake-build
        Start   1: ert_util_alloc_file_components
Test not available in configuration "cmake-build".
  1/114 Test   #1: ert_util_alloc_file_components .......***Not Run   0.00 sec
        Start   2: ert_util_split_path
Test not available in configuration "cmake-build".
...
Errors while running CTest
PS C:\dev\source\ecl\cmake-build> ctest --output-on-failure
Test project C:/dev/source/ecl/cmake-build
        Start   1: ert_util_alloc_file_components
Test not available without configuration.  (Missing "-C <config>"?)
  1/114 Test   #1: ert_util_alloc_file_components .......***Not Run   0.00 sec
        Start   2: ert_util_split_path
Test not available without configuration.  (Missing "-C <config>"?)
```

**Comment by dotfloat** [comment]
Oh, it seems to be a build configuration. I think it's `-C Release` or `-C "x64 Release"` or something. It's the MSVC build configuration.

**Comment by trhallam** [comment]
Ok cool, making progress.

I had to add the dll directory to the path in powershell
```
cd cmake-build
$Env:Path += ";"+$pwd+"\lib\Debug"
ctests --output-on-failure -C Debug
```

**Comment by trhallam** [comment]
So from the build output I think there are some unix dependencies not available on Windows. For example `unistd.h`:

```
C:\dev\source\ecl\lib\ecl\tests\test_transactions.cpp(21,10): fatal error C1083: Cannot open include file: 'unistd.h': No such
 file or directory [C:\dev\source\ecl\cmake-build\lib\test_transactions.vcxproj]
```

I was having a look around and there are options like this https://github.com/robinrowe/libunistd but I'm not exactly sure how to include it in available path cmake searches for. Can I just add it to the system path?

**Comment by dotfloat** [comment]
`unistd.h` should not be used by any Windows code. These probably come from the filesystem tests that failed. Today we added a C++17 requirement for tests, added a `Tmpdir` class, and all around made the superior `std::filesystem` available for use. These tests should be rewritten with `std::filesystem` in mind.

Have you attempted `pip install`ing the Python part of the library and getting anything from the `ecl` module to behave?

`Tmpdir`: https://github.com/equinor/ecl/blob/382d2dbbce495a34acfcabf258833e82b345f064/lib/tests/tmpdir.hpp

**Comment by trhallam** [comment]
Just tried a few different things with the Python installed.

Built a wheel using `python setup.py bdist_wheel` in a separate env and installed the wheel in a fresh env.
Tried `python setup.py install` and `python setup.py develop` in the fresh env.

All of these return an error on finding the `libecl.dll`. 

```
Python 3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 18:58:29) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ecl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\trhal\Anaconda3\envs\ecltest\lib\site-packages\ecl\__init__.py", line 95, in <module>
    class EclPrototype(Prototype):
  File "C:\Users\trhal\Anaconda3\envs\ecltest\lib\site-packages\ecl\__init__.py", line 96, in EclPrototype
    lib = dlopen_libecl()
  File "C:\Users\trhal\Anaconda3\envs\ecltest\lib\site-packages\ecl\__init__.py", line 92, in dlopen_libecl
    return ctypes.CDLL(path, ctypes.RTLD_GLOBAL)
  File "C:\Users\trhal\Anaconda3\envs\ecltest\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\trhal\Anaconda3\envs\ecltest\lib\site-packages\ecl\.bin\libecl.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

I checked, and the dll is built and definitely in the folder. Tried a few configurations in the `ecl\__init__.py` file. No luck, tried adding the `.bin` folder to the path and that didn't work either. Not sure why it's not working now.

**Comment by trhallam** [comment]
Ok, sorted out the last issue, apparently there are some security controls for loading dll on Windows. 

From the `ctypes` api:
_The winmode parameter is used on Windows to specify how the library is loaded (since mode is ignored). It takes any value that is valid for the Win32 API LoadLibraryEx flags parameter. When omitted, the default is to use the flags that result in the most secure DLL load to avoiding issues such as DLL hijacking. Passing the full path to the DLL is the safest way to ensure the correct library and dependencies are loaded._

After setting winmode=1 in the `CDLL` function of the `__init__.py` I was able to build install and import `ecl` functions.

The classes import ok but I get an access violation when trying to open the test data.
```
Python 3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 18:58:29) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ecl.grid import EclGrid
>>> EclGrid("faarikaal1.EGRID")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\trhal\Anaconda3\envs\ecltest\lib\site-packages\ecl\grid\ecl_grid.py", line 240, in __init__
    c_ptr = self._fread_alloc(filename, apply_mapaxes)
  File "C:\Users\trhal\Anaconda3\envs\ecltest\lib\site-packages\cwrap\prototype.py", line 218, in __call__
    return self._func(*args)
OSError: exception: access violation writing 0x00000000001A9FCE
>>> from ecl.eclfile import openEclFile
>>> openEclFile("farrikaal7.EGRID")
The function openEclFile is deprecated, use open_ecl_file.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\trhal\Anaconda3\envs\ecltest\lib\site-packages\ecl\eclfile\ecl_file.py", line 711, in openEclFile
    return open_ecl_file(file_name, flags)
  File "C:\Users\trhal\Anaconda3\envs\ecltest\lib\site-packages\ecl\eclfile\ecl_file.py", line 715, in open_ecl_file
    return EclFileContextManager(EclFile(file_name, flags))
  File "C:\Users\trhal\Anaconda3\envs\ecltest\lib\site-packages\ecl\eclfile\ecl_file.py", line 212, in __init__
    c_ptr = self._open( filename , flags )
  File "C:\Users\trhal\Anaconda3\envs\ecltest\lib\site-packages\cwrap\prototype.py", line 218, in __call__
    return self._func(*args)
OSError: exception: access violation writing 0x00000000001AA2C6
```

**Other Notes:**
Something was broken with `numpy` 1.19.4`  reverting to 1.18 fixed this.
```
RuntimeError: The current Numpy installation ('C:\\Users\\trhal\\Anaconda3\\envs\\ecltest\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```

**Comment by dotfloat** [comment]
Nice! Good find. With `python setup.py develop` or `python setup.py build_ext`, the DLLs should exist under `python/res/.libs` and `.bin`. This means you should be able to do `pytest python/tests`. I reckon it'll explode but should be fixable. There are no doubt functionality that tests for POSIX-only behaviour which I have no qualms about removing.

I'm away from my desktop with a Windows VM for the next two weeks so I won't be able to test any of this.

**Comment by trhallam** [comment]
This is the general gist of the `pytest` errors after using `python setup.py develop`

```
=========================================================================================== short test summary info ============================================================================================
ERROR ecl\util\test\test_area.py - cwrap.prototype.PrototypeError: Can not find function: test_work_area_alloc__ in library: <WinDLL 'C:\dev\source\ecl\python\ecl\.bin\libecl.dll', handle 7ffb25e70000 at 0x...
ERROR ecl\util\test\test_run.py - cwrap.prototype.PrototypeError: Type: 'test_area' already registered!
ERROR tests\bin_tests\test_summary_resample.py - cwrap.prototype.PrototypeError: Type: 'test_area' already registered!
ERROR tests\ecl_tests\test_cell.py - cwrap.prototype.PrototypeError: Type: 'test_area' already registered!
ERROR tests\ecl_tests\test_debug.py - cwrap.prototype.PrototypeError: Type: 'test_area' already registered!
```

**Comment by dotfloat** [comment]
Oh, this could be due to incorrect exports on the functions used by Python. Both on Linux and macOS (and most everything else) every symbol gets exported, while on Windows with MSVC one has explicitly export with `__declspec(dllexport)`. Likely this function doesn't have it set...

**Comment by trhallam** [comment]
What about this commit https://github.com/trhallam/ecl/commit/5d0e1ad15e8c9a4491d9a5f5169d3e12a0e6b02a "Disabled TestArea module with MSVC because it causes linker errors."

**Comment by dotfloat** [comment]
Most likely, yes. I'll try rewriting it to use `std::filesystem` later today/tomorrow.

**Comment by magnesj** [comment]
A PR including a build for Windows using GitHub Actions has now been merged. Please note that no tests are executed.
https://github.com/equinor/ecl/pull/806

**Comment by trhallam** [comment]
I tested this with a fresh install using scikit-build this afternoon and I was able to run my EclGrid EclSum and EclFile workflows OK. The same build errors as last time were not occurring.

**Comment by dotfloat** [comment]
> I had a play around with the pytest suite but it's too closely wound up with the C tests and the reliance on linux only libraries.I had a play around with the pytest suite but it's too closely wound up with the C tests and the reliance on linux only libraries.I had a play around with the pytest suite but it's too closely wound up with the C tests and the reliance on linux only libraries.I had a play around with the pytest suite but it's too closely wound up with the C tests and the reliance on linux only libraries.

**Comment by dotfloat** [comment]
I had another go at it, but had no luck. If we get funding for a Windows version then I'll be happy to try again, but as it stands now, the official suggestion is to use WSL if you're on Windows.

> I had a play around with the pytest suite but it's too closely wound up with the C tests and the reliance on linux only libraries.

We're not relying on any non-Windows libraries (namely only zlib), but rather we're relying on the OS being POSIX-compatible. Frustratingly, Windows is the only modern operating system that doesn't support POSIX.

> Pytest also seem to explicitly use the source instance of the code which means when using skbuild it can't find the DLL. This will either need to be pointed to manually or pytest could use an "installed" version of the library that had the dll in a findable location.

Yes. We get around this issue by creating a separate directory and symlinking some necessary directories over. See:
https://github.com/equinor/ecl/blob/3d6d17e1470419fc5af0c891560fb2211b2eda0d/.github/workflows/testing.yml#L92-L114

**Comment by trhallam** [comment]
I've had another go at this today with success as far as I can tell.

Not sure if you want me to submit a pull request but the edits I've made are here:
https://github.com/trhallam/ecl/commit/0c73bfa66413c29455fac5af5fbf9f3bfa152c57
and I've got a working wheel for Windows x64 available here
https://github.com/trhallam/ecl/releases/tag/v2.10.1

Key Issues:

- The `libecl.dll` ends up in `./.bin` not `./libs`.
- When using `ctypes.CDLL` to load `libecl.dll` there were problems identifying where `zlib.dll` is stored. I don't quite understand why but if I use `ctypes.OleDLL` to load `zlib.dll` explicitly first, the problem with `libecl.dll` goes away. I'm a bit confused because `zlib.dll` is on the same path as all the other dependencies. 
- Getting zlib recognized means the `winmode` flag is not required.
- As long as the development shell is active from Visual Studio building with scikit-build proceeds as usual via `python setup.py bdist_wheel`
- Also had to enable the environment variable `ECL_SKIP_SIGNAL` although I'm not strictly sure if this is necessary.

**Comment by dotfloat** [comment]
> * The `libecl.dll` ends up in `./.bin` not `./libs`.

CMake puts DLLs into the bin directory on Windows. You can change it here: https://github.com/equinor/ecl/blob/c361c259ee938d064b13e99065a6dbc01477cff0/setup.py#L75
Note that on Linux we need to have the binaries (from `applications/`) in the `.bin` directory. This is a Linux-only feature insofar that I couldn't figure out how to get RPATH to work properly on macOS.

> * When using `ctypes.CDLL` to load `libecl.dll` there were problems identifying where `zlib.dll` is stored. I don't quite understand why but if I use `ctypes.OleDLL` to load `zlib.dll` explicitly first, the problem with `libecl.dll` goes away. I'm a bit confused because `zlib.dll` is on the same path as all the other dependencies.

[OLE](https://en.wikipedia.org/wiki/Object_Linking_and_Embedding) is some Microsoft thing that this project should definitely not be using. From what I understand it's used to embed views into other programs, eg. inserting a chart from Microsoft Excel into Microsoft Word.

`ctypes.WinDLL` is probably what you're looking for. I would imagine that MSVC uses `stdcall` by default, so `ctypes.WinDLL` is the way to go.

As for not being able to find `zlib.dll`, you should try using [auditwheel](https://github.com/pypa/auditwheel). It's the program that is used to finalise Python wheels. One of the things it does is that it embeds every non-standard library into the `.whl`, in a way that Python can later figure it out.

```bash
pip wheel . --no-deps -w dist  # Make a wheel for ecl (and only ecl due to --no-deps), write result into dist/
auditwheel repair dist/*  # Repair everything in the dist/ directory
```

> * Getting zlib recognized means the `winmode` flag is not required.

I'm not certain what this flag does.`ecl` already opens the library using an absolute path, so no hijacking can happen (I think).

> * Also had to enable the environment variable `ECL_SKIP_SIGNAL` although I'm not strictly sure if this is necessary.

The signal hijacking of `ecl` has given us so much headaches that I would like to have any excuse to rip it out. We already use `ECL_SKIP_SIGNAL` in our downstream projects, and we're only keeping it because we're scared that someone relies on this feature.

**Comment by crayxt** [comment]
@dotfloat It seems like auditwheel only support Linux

**Comment by eivindjahren** [comment]
There are windows wheels available on pypi now.
